server:
  port: 9999
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
      - id: customer-user
        uri: lb://customer-user
        predicates:
          - Path=/gateway/**
        filters:
          - StripPrefix=1
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
